trigger:
  batch: true
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    exclude:
    - docs/oops-this-one-no-longer-exists.md
    - README.md

resources:
  repositories:
  - repository: self

stages:
  - stage: build
    displayName: 'Build, Test, and Deploy'
    jobs:
      - job: 'build_test_deploy_DEV'
        displayName: 'Build, test, and deploy to Dev'
        condition: eq('${{ parameters.Environment }}', 'dev')
  
        pool:
          vmImage: 'ubuntu-latest'
  
        variables:
          - group: super_awesome_project_keyvault_variable_group_deV
          # Hey, if you change ^^^ that line, I just realized, we standardized on dashes ("-")
          # instead of underscores ("_") for variable group names.  Can you change that too, please?
  
        steps:
        - bash: echo "This is not a very useful build script"
          displayName: 'Super-useful build script'